# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name:  "🚢 Lint & Build"

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    # Cache for nextjs: https://nextjs.org/docs/messages/no-cache#github-actions
    - uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

    - run: npm ci
    - run: npm run lint
    - run: npm run build --if-present
    - run: docker build -t ${{ github.repository }}:latest .
