# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name:  "📦 Build container"

on: 
  workflow_call:
    inputs:
      registry:
        required: false
        type: string
        default: ghcr.io
        description: "The container registry to use, defaults to github packages"
      image-name:
        required: false
        type: string
        default: ${{ github.repository }}
        description: "The name of the image, should include project/namespace, if any."
      push:
        required: false
        type: boolean
        default: false
        description: "If push to registry should be performed"
      docker-file:
        required: false
        type: string
        default: Dockerfile
        description: "Path to the dockerfile used for building the container, relative to git context"

jobs:

  build-container:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.registry }}/${{ env.image-name }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        # Do we need to parameterize context?
        context: . 
        push: ${{ inputs.push }}
        file: ${{ inputs.docker-file }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
