# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name:  "🚢 Lint & Build"

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'

    - run: npm ci
    - run: npm run lint
    - run: npm run build --if-present
