# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name:  "📄 Create HelmRelease manifest"

on: 
  workflow_call:
    inputs:
      name:
        required: false
        type: string
        default: ${{ github.event.repository.name }}
        description: "Name of the generated HelmRelease"
      chart-source:
        required: false
        type: string
        default: "HelmRepository/visegue-public"
        description: "The named repository (source in flux) that the chart will be read from"
      chart:
        required: false
        type: string
        default: ${{ github.event.repository.name }}
        description: "The chart used in the HelmRelease manifest."
      chart-version:
        required: false
        type: string
        default: ${{ github.ref_name }}
        description: "The chart version used in the HelmRelease manifest."
      namespace:
        required: false
        type: string
        default: "public-apps"
        description: "The namespace used for applying the HelmRelease manifest"
      interval:
        required: false
        type: string
        default: "10m"
        description: "The flux sync interval for the generated HelmRelease"
      value-files:
        required: false
        type: string
        default: "./helm/values/values.yaml"
        description: "Comma separeted list of search paths of value files used for the chart, no whitespace. Paths relative to the workspace"
      artifact-name:
        required: false
        type: string
        default: "helmrelease"
        description: "Name of the generated helmrelease artifact, can be used in other jobs or downloaded manually"

env:
  output-file: ${{ inputs.name }}-helmrelease.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fluxcd/flux2/action@main
      with:
          version: 0.30.2
    - name: Generate values list
      # Works because github does expansion of the variable ${{ input.value-files }} before the actual brace expansion takes places.
      # Usual evaluation order evaluates brace expansion before variable expansion, this can be solved by using eval command:
      # https://www.datafix.com.au/BASHing/2020-04-22.html
      # But that is not needed now that github expands the varible before the command is run.
      run: echo "::set-output name=values::--values={${{ inputs.value-files }}}"
      id: values_list
    - name: Run Flux commands
      run: flux create hr ${{ inputs.name }} --source=${{ inputs.chart-source }} --chart=${{ inputs.chart }} --chart-version=${{ inputs.chart-version }} ${{ steps.values_list.outputs.values }} --interval=${{ inputs.interval }} --namespace=${{ inputs.namespace }} --export > ${{ env.output-file }}
    - name: Upload Generated HelmRelease as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ env.output-file }}
        retention-days: 5
