# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name:  "📄 Generate HelmRelease manifest"

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fluxcd/flux2/action@main
      with:
          version: 0.30.2
    - name: Run Flux commands
      run: flux create hr pipeline-lab --source=HelmRepository/visegue-public --chart=pipeline-lab --values=./helm/values/values.yaml --values=./helm/values/values-staging.yaml --interval=10m --namespace=demo-staging --export
