# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name:  "📄 Generate HelmRelease manifest"

on: 
  workflow_call:
    inputs:
      name:
        required: false
        type: string
        default: ${{ github.event.repository.name }}
        description: "Name of the generated HelmRelease"
      chart-source:
        required: false
        type: string
        default: "HelmRepository/visegue-public"
        description: "The named repository (source in flux) that the chart will be read from"
      chart:
        required: false
        type: string
        default: ${{ github.event.repository.name }}
        description: "The chart used in the HelmRelease manifest (that will be used for deploy)."
      namespace:
        required: false
        type: string
        default: "default"
        description: "The namespace used for applying the HelmRelease manifest"
      interval:
        required: false
        type: string
        default: "10m"
        description: "The flux sync interval for the generated HelmRelease"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fluxcd/flux2/action@main
      with:
          version: 0.30.2
    - name: Run Flux commands
      run: flux create hr ${{ inputs.name }} --source=${{ inputs.chart-source }} --chart=${{ inputs.chart }} --values=./helm/values/values.yaml --values=./helm/values/values-staging.yaml --interval=${{ inputs.interval }} --namespace=${{ inputs.namespace }} --export
