# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name:  "📄 Generate HelmRelease manifest"

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Flux CLI
      uses: fluxcd/flux2/action@main
      with:
          version: 0.30.2
    - name: Run Flux commands
      run: flux -v
