# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "📦 Release"

on: 
  workflow_call:
    secrets:
      release-gh-token:
        description: 'Github token used when running semantic release, should have push back privileges to the repo'
        required: true
      helm-repository-username:
        description: 'Username if/when pushing helm charts'
        required: false
      helm-repository-password:
        description: 'Username if/when pushing helm charts'
        required: false
      container-registry-username:
        description: 'Username if/when pushing build container'
        required: false
      container-registry-password:
        description: 'Password if/when pushing build container'
        required: false
        

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # If we persist credentials at checkokut, the GITHUB_TOKEN later down don't take
        # see: https://github.com/semantic-release/git/issues/196
        persist-credentials: false  
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    # Cache for nextjs: https://nextjs.org/docs/messages/no-cache#github-actions
    - uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
    
    - run: npm ci

    - name: Create release using semantic release
      run: npx semantic-release       
      env:
        GITHUB_TOKEN: ${{ secrets.release-gh-token }}
        HUSKY: 0
        REGISTRY_USERNAME: ${{ secrets.helm-repository-username }}
        REGISTRY_PASSWORD: ${{ secrets.helm-repository-password }}
        DOCKER_REGISTRY_USER: ${{ secrets.container-registry-username }}
        DOCKER_REGISTRY_PASSWORD: ${{ secrets.container-registry-password }}
