name: '🧬 Build and release'

on:
  push:

# We currently run release on all branches, shouldn't be a problem as
# Semantic release is configured to have prerelease and release branches
# in itself.
# If it's not a prerelease/release branch, nothing should happen.
# To save up on action minutes and get a cleaner run history it
# would be possible to specify different files for different branches
# (build for dev branch, build+release for release branches).
# But then the action file branches need to be syncronized with the
# semantic-release configuration.

jobs:
  call-lint-and-build:
    uses: ./.github/workflows/_build.yml@main

  call-tests:
    needs: call-lint-and-build
    uses: ./.github/workflows/_test.yml@main
  
  call-release:
    needs: call-tests
    uses: ./.github/workflows/_release.yml@main
    secrets:
      release-gh-token: ${{ secrets.PUBLIC_RELEASE_TOKEN }}
