name: '🧬 Build and release'

on:
  push:

# We currently run release on all branches, shouldn't be a problem as
# Semantic release is configured to have prerelease and release branches
# in itself.
# If it's not a prerelease/release branch, nothing should happen.
# To save up on action minutes and get a cleaner run history it
# would be possible to specify different files for different branches
# (build for dev branch, build+release for release branches).
# But then the action file branches need to be syncronized with the
# semantic-release configuration.

jobs:
  call-lint-and-build:
    uses: ./.github/workflows/_build.yml

  call-build-container:
    uses: ./.github/workflows/_build-container.yml

  call-test:
    uses: ./.github/workflows/_test.yml
  
  call-release:
    needs: [call-lint-and-build, call-build-container, call-test] 
    uses: ./.github/workflows/_release.yml
    secrets:
      release-gh-token: ${{ secrets.PUBLIC_RELEASE_TOKEN }}
      container-registry-username: ${{ secrets.PUBLIC_REGISTRY_USERNAME }}
      container-registry-password: ${{ secrets.PUBLIC_REGISTRY_PASSWORD }}
      helm-repository-username: ${{ secrets.PUBLIC_REGISTRY_USERNAME }}
      helm-repository-password: ${{ secrets.PUBLIC_REGISTRY_PASSWORD }}

  call-create-manifest:
    uses: ./.github/workflows/_create-helm-release-manifest.yml
    with:
      namespace: "demo-staging"
      value-files: "./helm/values/values.yaml,helm/values/values-staging.yaml"
