name: Cleanup branch resources

on: [delete]

jobs:
  cleanup:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-18.04
    steps:
      - name: Clean up
        run: |
          echo "Clean up for branch ${{ github.event.ref }}"