# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Deploy staging

on:
  release:
    # Note: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
    # If not working well with prereleased/release types, used publish and check event instead
    # Prereleases created from drafts don't trigger prerelease, but publish will. But not
    # currently using that workflow 
    types: [prereleased]  
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        # If we persist credentials at checkokut, the GITHUB_TOKEN later down don't take
        # see: https://github.com/semantic-release/git/issues/196
        # true for semantic-release, needed here?
        persist-credentials: false  

    - name: Deploy to staging
      run: |
        echo "Deploying ${{ github.event.release.tag_name }} to staging"
    
    - name: Automatic verification of staging
      run: |
        echo "Verified"
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ env.GITHUB_TOKEN }}
        commit-message: "chore: merge to ${{ github.event.repository.default_branch }}"
        branch: ${{ github.event.release.target_commitish }}
        title: Ready for release
        body: This release candidate is ready to be released, merge to start release process
        reviewers: ${{ github.actor }}
        base: ${{ github.event.repository.default_branch }}
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}
