# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "📨 Deploy preview"

on:
  pull_request:

env:
  IMAGE: "${{ secrets.registry }}/${{ github.event.repository.name }}:pr-${{ github.event.pull_request.number }}"

jobs:
  build-preview:
    runs-on: ubuntu-latest
  
    steps:
    - name: Prepare preview
      run: |
        echo "Prepare whatever is needed to deploy preview: ${{ env.IMAGE }}"

  call-deploy-preview:
    needs: build-preview
    uses: ./.github/workflows/_deploy.yml
    with:
      image: ${{ env.IMAGE }}
      environment: preview
