# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "🚢 Deploy prerelease"

on:
  release:
    types: [prereleased]
   
jobs:
  call-create-manifest:
    uses: ./.github/workflows/_create-helm-release-manifest.yml
    with:
      namespace: "public-apps-staging"
      value-files: "./helm/values/values.yaml,helm/values/values-staging.yaml"

  call-deploy:
    uses: ./.github/workflows/_deploy-manifests.yml
    needs: [call-create-manifest]
    with:
      target-path: staging/
    secrets:
      deploy-gh-token: ${{ secrets.PUBLIC_RELEASE_TOKEN }}

