# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Deploy staging

on:
  release:
    # Note: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
    # If not working well with prereleased/release types, used publish and check event instead
    # Prereleases created from drafts don't trigger prerelease, but publish will. But not
    # currently using that workflow 
    types: [prereleased]  
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to staging
      run: |
        echo "Deploying ${{ github.event.release.tag_name }} to staging"
    - name: Automatic verification of staging
      run: |
        echo "Verified"
    
  pull-request:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - uses: actions/checkout@v2
      with:
        # If we persist credentials at checkokut, the GITHUB_TOKEN later down don't take
        # see: https://github.com/semantic-release/git/issues/196
        persist-credentials: false  
    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ${{ github.event.release.target_commitish }}
        destination_branch: ${{ github.event.repository.default_branch }}                      
        pr_title: "Pulling ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
        pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
        pr_reviewer: ${{ github.actor }}
        pr_allow_empty: true                              # Creates pull request even if there are no changes

