# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "🚢 Deploy prerelease"

on:
  release:
    types: [prereleased]

env:
  REGISTRY: ghcr.io
  PROJECT: visegue
  IMAGE_NAME: ${{ github.repository }}
  TAG: ${{ github.event.release.tag_name }}
    
jobs:
  # Unable to use env directly in input:
  # https://github.com/actions/runner/issues/480#issuecomment-1021278915
  
  call-deploy-staging:
    uses: ./.github/workflows/_deploy-staging.yml
    with:
      image: "$REGISTRY/$PROJECT/$IMAGE_NAME:$TAG"
