# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "🚀 Deploy release"

on:
  release:
    types: [released]

jobs:
  call-create-manifest:
    uses: ./.github/workflows/_create-helm-release-manifest.yml
    with:
      namespace: "public-apps"
      value-files: "./helm/values/values.yaml"

  call-deploy:
    uses: ./.github/workflows/_deploy-manifests.yml
    needs: [call-create-manifest]
    with:
      target-path: production/
    secrets:
      deploy-gh-token: ${{ secrets.PUBLIC_RELEASE_TOKEN }}
