# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "📨 Deploy preview"

on:
  pull_request:

jobs:
  # Used as a result of not being able to map environments directly as input:
  # https://github.com/actions/runner/issues/480#issuecomment-1021278915
  setup-image:
    uses: ./.github/workflows/_generate-image-name.yml
    with:
      tag: "pr-${{ github.event.pull_request.number }}"

  build-preview:
    runs-on: ubuntu-latest
    needs: [setup-image]
    steps:
    - name: Prepare preview
      run: |
        echo "Prepare whatever is needed to deploy preview: ${{ needs.setup-image.outputs.name }}
    
    
  call-deploy-preview:
    needs: [setup-image, build-preview]
    uses: ./.github/workflows/_deploy.yml
    with:
      image: ${{ needs.setup-image.outputs.name }}
      environment: preview
