# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "🚢 Deploy prerelease"

on:
  release:
    types: [prereleased]

env:
  IMAGE: "${{ secrets.PUBLIC_REGISTRY_URL }}/${{ github.event.repository.name }}:${{ github.event.release.tag_name }}"
    
jobs:
  call-deploy-staging:
    uses: ./.github/workflows/_deploy-staging.yml
    with:
      image: ${{ env.IMAGE }}
      