# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "📨 Deploy preview"

on:
  pull_request:

jobs:
  # Used as a result of not being able to map environments directly as input:
  # https://github.com/actions/runner/issues/480#issuecomment-1021278915
  # Would rather use env variables without mapping outputs, it gets messy quick.
  # There are other alternatives that might be better, eg:
  # - Read environments directly in shared files
  # - Map env files to outputs
  # - Split one image to several inputs for deploy (registry, project, name, tag)
  call-setup-image:
    uses: ./.github/workflows/_generate-image-name.yml@main
    with:
      tag: "pr-${{ github.event.pull_request.number }}"

  build-preview:
    runs-on: ubuntu-latest
    needs: [call-setup-image]
    steps:
    - name: Prepare preview
      run: |
        echo "Prepare whatever is needed to deploy preview: ${{ needs.call-setup-image.outputs.image }}"
    
    
  call-deploy-preview:
    needs: [call-setup-image, build-preview]
    uses: ./.github/workflows/_deploy.yml@main
    with:
      image: ${{ needs.call-setup-image.outputs.image }}
      environment: preview
