# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Deploy preview

on:
  pull_request:
    branches-ignore: # Main branches deploy to staging
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy preview 
      run: echo "Deploy blaha-${{ github.event.number }}"

    - name: Verify preview 
      run: Running automatic tests against preview
