# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release

on:
  workflow_run:
    workflows: 
    - "Build"
    types: 
    - "completed"
    # Could possibly skip branches as an actual release will only be made if its warranted and
    # on the correct branches anyway. But have the branches explicitly to keep the actions
    # sections cleaner (otherwise it would still show a run release action, which won't do anything else
    # but confirm that a release isn't needed).
    # The release workflow could be a job in the build workflow instead, maybe cleaner?
    branches: 
    - "rc"
    - "main"
    - "master"
    
jobs:
  release:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        # If we persist credentials at checkokut, the GITHUB_TOKEN later down don't take
        # see: https://github.com/semantic-release/git/issues/196
        persist-credentials: false  
    
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Setup dependencies
      run: npm ci
    
    - name: Build for release
      run: npm run build
      # Create prerelease, for configuratino see .releaserc file
    
    - name: Create release using semantic release
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLIC_RELEASE_TOKEN }}
        GH_TOKEN: ${{ secrets.PUBLIC_RELEASE_TOKEN }}
        HUSKY: 0
      run: npx semantic-release       
